//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyPythonIde.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasyPythonIde.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Avatar150 {
            get {
                object obj = ResourceManager.GetObject("Avatar150", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 未检测到同捆Python解释器，将会尝试使用系统自带版本 的本地化字符串。
        /// </summary>
        internal static string BundlePyhton_NotFound {
            get {
                return ResourceManager.GetString("BundlePyhton_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已成功检测到目录下同捆Python解释器 的本地化字符串。
        /// </summary>
        internal static string BundlePython_Found {
            get {
                return ResourceManager.GetString("BundlePython_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Python解释器检测 的本地化字符串。
        /// </summary>
        internal static string BundlePython_MessageCaption {
            get {
                return ResourceManager.GetString("BundlePython_MessageCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开 的本地化字符串。
        /// </summary>
        internal static string Button_Open {
            get {
                return ResourceManager.GetString("Button_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运行 的本地化字符串。
        /// </summary>
        internal static string Button_Run {
            get {
                return ResourceManager.GetString("Button_Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 的本地化字符串。
        /// </summary>
        internal static string Button_Save {
            get {
                return ResourceManager.GetString("Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法执行空命令 的本地化字符串。
        /// </summary>
        internal static string CannotExecuteNull {
            get {
                return ResourceManager.GetString("CannotExecuteNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出现运行错误 的本地化字符串。
        /// </summary>
        internal static string CannotExecuteNull_Caption {
            get {
                return ResourceManager.GetString("CannotExecuteNull_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (已修改) -  的本地化字符串。
        /// </summary>
        internal static string CaptionJoin_Edited {
            get {
                return ResourceManager.GetString("CaptionJoin_Edited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 临时文件模式 -  的本地化字符串。
        /// </summary>
        internal static string CaptionJoin_TempRun {
            get {
                return ResourceManager.GetString("CaptionJoin_TempRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  -  的本地化字符串。
        /// </summary>
        internal static string CaptionJoin_Unedited {
            get {
                return ResourceManager.GetString("CaptionJoin_Unedited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 untitle.py 的本地化字符串。
        /// </summary>
        internal static string DefaultFileName {
            get {
                return ResourceManager.GetString("DefaultFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 profile.xml 的本地化字符串。
        /// </summary>
        internal static string ProfilePath {
            get {
                return ResourceManager.GetString("ProfilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配置文件已损坏,是否删除? 的本地化字符串。
        /// </summary>
        internal static string ProfileReadError {
            get {
                return ResourceManager.GetString("ProfileReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配置文件读取错误 的本地化字符串。
        /// </summary>
        internal static string ProfileReadError_Caption {
            get {
                return ResourceManager.GetString("ProfileReadError_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配置文件写入错误,请尝试手动删除程序目录下的 的本地化字符串。
        /// </summary>
        internal static string ProfileWriteError {
            get {
                return ResourceManager.GetString("ProfileWriteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配置文件写入错误 的本地化字符串。
        /// </summary>
        internal static string ProfileWriteError_Caption {
            get {
                return ResourceManager.GetString("ProfileWriteError_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EasyPython 的本地化字符串。
        /// </summary>
        internal static string ProgramName {
            get {
                return ResourceManager.GetString("ProgramName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 控制台程序运行中... 的本地化字符串。
        /// </summary>
        internal static string RunCmd_Title {
            get {
                return ResourceManager.GetString("RunCmd_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Python脚本运行中... 的本地化字符串。
        /// </summary>
        internal static string RunCmdPython_Title {
            get {
                return ResourceManager.GetString("RunCmdPython_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否要先保存脚本文件再退出?(否则将会失去该文件的最新版本) 的本地化字符串。
        /// </summary>
        internal static string SaveBeforeExit {
            get {
                return ResourceManager.GetString("SaveBeforeExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 脚本文件未保存 的本地化字符串。
        /// </summary>
        internal static string SaveBeforeExit_Caption {
            get {
                return ResourceManager.GetString("SaveBeforeExit_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否要先保存脚本文件再运行?(否则会运行该文件的上一版本) 的本地化字符串。
        /// </summary>
        internal static string SaveBeforeRun {
            get {
                return ResourceManager.GetString("SaveBeforeRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 脚本文件未保存 的本地化字符串。
        /// </summary>
        internal static string SaveBeforeRun_Caption {
            get {
                return ResourceManager.GetString("SaveBeforeRun_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第 的本地化字符串。
        /// </summary>
        internal static string StatisticLabel_pt1 {
            get {
                return ResourceManager.GetString("StatisticLabel_pt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 行,第 的本地化字符串。
        /// </summary>
        internal static string StatisticLabel_pt2 {
            get {
                return ResourceManager.GetString("StatisticLabel_pt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 列,共 的本地化字符串。
        /// </summary>
        internal static string StatisticLabel_pt3 {
            get {
                return ResourceManager.GetString("StatisticLabel_pt3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 行 的本地化字符串。
        /// </summary>
        internal static string StatisticLabel_pt4 {
            get {
                return ResourceManager.GetString("StatisticLabel_pt4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用临时文件模式可以更加方便的进行调试,但是有可能会造成数据丢失,是否仍要开启此开关? 的本地化字符串。
        /// </summary>
        internal static string TempRunConfirm {
            get {
                return ResourceManager.GetString("TempRunConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不应在实用环境中使用临时文件模式运行 的本地化字符串。
        /// </summary>
        internal static string TempRunConfirm_Caption {
            get {
                return ResourceManager.GetString("TempRunConfirm_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://github.com/shirok1/easy-python-ide 的本地化字符串。
        /// </summary>
        internal static string UrlGithubRepo {
            get {
                return ResourceManager.GetString("UrlGithubRepo", resourceCulture);
            }
        }
    }
}
